const icons = [
  'smile', 'cry', 'success', 'warning', 'prompt', 'error',
  'help', 'clock', 'success-filling', 'delete-filling', 'favorites-filling',
  'add', 'minus', 'arrow-up', 'arrow-down', 'arrow-left', 'arrow-right', 'arrow-double-left',
  'arrow-double-right', 'switch', 'sorting', 'descending', 'ascending', 'select', 'semi-select',
  'loading', 'search', 'close', 'ellipsis', 'picture', 'calendar', 'ashbin', 'upload', 'download',
  'set', 'edit', 'refresh', 'filter', 'attachment', 'account', 'email', 'atm',
  'account-settings', 'add-doc', 'add-filling', 'admin', 'airplane', 'alert', 'align-center',
  'align-justify', 'align-left', 'align-right', 'appointment', 'appointment-check', 'arrow-down-circled', 'arrow-up-circled',
  'at', 'audio', 'backspace', 'badge', 'bonus', 'book',
  'bookmark', 'border-dashed', 'border-dotted', 'border-solid', 'brand-alipay', 'brand-aliwayer',
  'brand-aliyun', 'brand-android', 'brand-ant', 'brand-apple', 'brand-chrome', 'brand-dingding',
  'brand-ie', 'brand-qianniu', 'brand-taobao', 'brand-tmall', 'brand-uc', 'brand-wangwang',
  'brand-xiaomi', 'briefcase', 'brush', 'building', 'bus', 'button',
  'button-group', 'calendar-span', 'camera', 'car', 'card','cascade',
  'certificate', 'certificate-type', 'chart-funnel', 'chart-gauge', 'chart-line', 'chart-radar',
  'check', 'checkbox', 'chinese-circled', 'clean', 'code', 'code-js',
  'collapse-panel', 'collapse-square', 'columns', 'command', 'comment', 'container',
  'cry-filling', 'custom-list', 'cut', 'data-settings', 'debug', 'deploy',
  'design', 'desktop', 'dialog', 'dingding', 'direction-bottom', 'direction-bottom-left',
  'direction-bottom-right', 'direction-left', 'direction-right', 'direction-top', 'direction-top-left', 'direction-top-right',
  'document', 'drawer', 'dropdown', 'dropdown-menu', 'dropper', 'employee-add',
  'employee-search', 'employee-select', 'english-circled', 'entry', 'exchange', 'expand-square',
  'fanyi', 'favorite', 'favorite-filling', 'float-clear-both', 'float-clear-left', 'float-clear-right',
  'float-left', 'float-right', 'flow-branch', 'flow-condition', 'flow-connect', 'flow-end-point',
  'flow-start-point', 'folder', 'font-family', 'font-size', 'fullscreen-off', 'fullscreen-on',
  'function', 'group', 'hamburger', 'hammer', 'handset', 'handset-filling',
  'help-filling', 'home', 'i18n', 'image', 'image-upload', 'inherited-fields',
  'input', 'invisible', 'invoice', 'iterator', 'key', 'keyboard',
  'laptop', 'layers', 'legend-bottom-center', 'legend-bottom-left', 'legend-bottom-right', 'legend-top-center',
  'legend-top-left', 'legend-top-right', 'lifebuoy', 'link', 'link-block', 'link-out',
  'list-container', 'locate', 'location', 'matrix', 'mentions', 'menu',
  'menu-collapse', 'menu-expand', 'menu-with-icon', 'mesh', 'mesh-dense', 'meta-panel',
  'metadata', 'microphone', 'mobile', 'money-circled', 'more', 'multi-select',
  'name-card', 'nav-bottom', 'nav-left', 'nav-right', 'nav-top', 'news',
  'notice', 'notice-filling', 'number-input', 'number-set', 'number0', 'number0-filling',
  'number1', 'number1-filling', 'number10', 'number10-filling', 'number2', 'number2-filling',
  'number3', 'number3-filling', 'number4', 'number4-filling', 'number5', 'number5-filling',
  'number6', 'number6-filling', 'number7', 'number7-filling', 'number8', 'number8-filling',
  'number9', 'number9-filling', 'outline', 'overflow-auto', 'overflow-scroll', 'page',
  'page-header', 'pagination', 'paste', 'permission-review', 'permissions', 'player-pause',
  'player-start', 'player-stop', 'position-absolute', 'position-bottom', 'position-bottom-left', 'position-bottom-right',
  'position-fixed', 'position-full', 'position-left', 'position-relative', 'position-right', 'position-top',
  'position-top-left', 'position-top-right', 'printer', 'process', 'progress', 'prompt-filling',
  'radio', 'reading', 'redo', 'remove-circled', 'remove-filling', 'richtext',
  'rotate-left', 'rotate-right', 'safari', 'save', 'scan', 'scan-ar',
  'shop', 'shopping-cart', 'slide', 'smart-watch', 'smile-filling', 'sort-asc',
  'sort-desc', 'stamp', 'star', 'star-filling', 'steps', 'table',
  'tabs', 'team', 'telephone', 'template', 'text', 'text-bold',
  'text-strikeout', 'text-underline', 'textarea', 'thumb', 'timeline', 'title',
  'toolbar', 'tooltip', 'totop', 'transfer', 'translate', 'translate-filling',
  'travel', 'tree', 'tree-select', 'triangle-down', 'triangle-left', 'triangle-right',
  'triangle-up', 'tv', 'undo', 'urge', 'vacation', 'var',
  'video', 'view-collapse', 'view-detail', 'view-expand', 'visible', 'warning-filling',
  'webcam', 'zoom-in', 'zoom-out', 'male', 'female', 'insert', 'insert-sub'
]

export {
  icons
}
